import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {createApp} from '../server/index.mjs';
import {id,passwordHash} from '../server/db.mjs';
test('authenticated API enforces roles, server prices and booking conflicts',async()=>{
 const {server,db}=createApp({dbPath:':memory:'});server.listen(0,'127.0.0.1');await once(server,'listening');const base=`http://127.0.0.1:${server.address().port}/api`;
 const call=async(path,method='GET',body,token)=>{const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,body:await r.json()}};
 try{const uid=id();db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,?,?)').run(uid,'owner@example.com','Owner',passwordHash('Strong-password-123'),'system',null,1,new Date().toISOString());
 assert.equal((await call('/admin/state')).status,401);
 assert.equal((await call('/auth/login','POST',{email:'owner@example.com',password:'wrong'})).status,401);
 const owner=(await call('/auth/login','POST',{email:'owner@example.com',password:'Strong-password-123'})).body.token;
 const s=(await call('/admin/stores','POST',{name:'Actual Rental Shop',city:'Amman',email:'shop@example.com'},owner)).body;
 assert.equal(s.status,'pending');await call('/admin/stores/'+s.id,'PATCH',{status:'active'},owner);
 const other=(await call('/admin/stores','POST',{name:'Other Shop',city:'Irbid',email:'other@example.com'},owner)).body;await call('/admin/stores/'+other.id,'PATCH',{status:'active'},owner);
 const admin=(await call('/admin/users','POST',{name:'Shop Manager',email:'manager@example.com',password:'Strong-password-456',storeId:s.id},owner)).body;
 const shop=(await call('/auth/login','POST',{email:'manager@example.com',password:'Strong-password-456'})).body.token;
 assert.equal((await call('/admin/settings','PUT',{deliveryFee:1,promotion:'attack'},shop)).status,403);
 const car=(await call('/admin/cars','POST',{name:'Toyota',category:'Comfort',price:45,deposit:50,eta:'30–45',image:'/images/camry.jpg',description:'Rental vehicle',seats:5,status:'available',storeId:other.id},shop)).body;
 assert.equal(car.storeId,s.id,'shop cannot forge another store association');
 const c=(await call('/auth/register','POST',{name:'Customer',email:'customer@example.com',password:'Customer-pass-123',role:'system'})).body;assert.equal(c.user.role,'customer');
 const c2=(await call('/auth/register','POST',{name:'Other',email:'othercustomer@example.com',password:'Customer-pass-123'})).body;
 assert.equal((await call('/admin/state','GET',null,c.token)).status,403);
 const payload={carId:car.id,start:'2027-01-10',end:'2027-01-12',delivery:true,address:'Test street',phone:'+962 79 123 4567',payment:'Cash',total:1,deposit:0};
 const booked=await call('/bookings','POST',payload,c.token);assert.equal(booked.status,201);assert.equal(booked.body.total,95);assert.equal(booked.body.deposit,50);
 const duplicate=(await call('/bookings','POST',payload,c2.token)).body;
 assert.equal((await call('/bookings/'+booked.body.id,'PATCH',{status:'approved'},c.token)).status,403);
 assert.equal((await call('/bookings/'+booked.body.id,'PATCH',{status:'approved'},shop)).status,200);
 assert.equal((await call('/bookings/'+duplicate.id,'PATCH',{status:'approved'},shop)).status,409);
 assert.equal((await call('/bookings','POST',payload,c.token)).status,409);
 assert.equal((await call('/bookings','GET',null,c2.token)).body.length,1);
 assert.equal((await call('/bookings/'+booked.body.id,'PATCH',{status:'cancelled'},c2.token)).status,403);
 assert.equal((await call('/admin/cars/'+car.id,'DELETE',{},shop)).status,409);
 assert.equal((await call('/admin/cars/'+car.id,'PUT',{...car,status:'maintenance'},shop)).status,409);
 assert.equal((await call('/reviews','POST',{bookingId:booked.body.id,rating:5,text:'Great'},c.token)).status,403);
 await call('/bookings/'+booked.body.id,'PATCH',{status:'completed'},shop);
 assert.equal((await call('/reviews','POST',{bookingId:booked.body.id,rating:5,text:'Great'},c.token)).status,201);
 assert.equal((await call('/catalog')).body.reviews.length,0);
 const review=(await call('/admin/state','GET',null,owner)).body.reviews[0];await call('/admin/reviews/'+review.id,'PATCH',{status:'published'},owner);assert.equal((await call('/catalog')).body.reviews.length,1);
 await call('/admin/stores/'+s.id,'PATCH',{status:'suspended'},owner);assert.equal((await call('/catalog')).body.cars.length,0);assert.equal((await call('/admin/state','GET',null,shop)).status,403);
 await call('/admin/users/'+admin.id,'PATCH',{active:false},owner);assert.equal((await call('/auth/login','POST',{email:'manager@example.com',password:'Strong-password-456'})).status,401);
 await call('/auth/logout','POST',{},c.token);assert.equal((await call('/bookings','GET',null,c.token)).status,401);
 }finally{server.close();await once(server,'close');db.close()}
});
