import {createServer} from 'node:http';
import {readFileSync,existsSync} from 'node:fs';
import {resolve,extname,sep} from 'node:path';
import {randomBytes} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {openDb,id,passwordHash,verifyPassword,hashToken,publicUser,registerCustomer} from './db.mjs';
import {seedDemo} from './seed.mjs';
const ROOT=resolve(fileURLToPath(new URL('..',import.meta.url)));
class ApiError extends Error{constructor(status,message){super(message);this.status=status;}}
const fail=(status,message)=>{throw new ApiError(status,message)};
const text=(value,name,max=200)=>{if(typeof value!=='string'||!value.trim()||value.length>max)fail(400,`Invalid ${name}`);return value.trim();};
const email=value=>{const v=text(value,'email').toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))fail(400,'Invalid email');return v};
const num=(value,name,min,max)=>{if(typeof value!=='number'||!Number.isFinite(value)||value<min||value>max)fail(400,`Invalid ${name}`);return value};
const choice=(value,list,name)=>{if(!list.includes(value))fail(400,`Invalid ${name}`);return value};
const date=value=>{if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value))fail(400,'Invalid date');const timestamp=Date.parse(value+'T00:00:00Z');if(!Number.isFinite(timestamp)||new Date(timestamp).toISOString().slice(0,10)!==value)fail(400,'Invalid date');return value};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dubai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const parse=row=>JSON.parse(row.payload);
async function body(req){let chunks=[],size=0;for await(const chunk of req){size+=chunk.length;if(size>3*1024*1024)fail(413,'Request is too large');chunks.push(chunk);}try{return JSON.parse(Buffer.concat(chunks).toString()||'{}')}catch{fail(400,'Invalid JSON')}}
export function createApp({dbPath=process.env.DATABASE_PATH||resolve(ROOT,'.runtime/ridelink.sqlite'),origin=process.env.APP_ORIGIN||'http://127.0.0.1:5173',secure=process.env.NODE_ENV==='production'}={}){
const db=openDb(dbPath);seedDemo(db);const limits=new Map();
// This in-memory limiter resets on restart and is per-instance; deployment assumes a single API instance.
function rate(req,kind,max=12){const k=kind+':'+req.socket.remoteAddress;const now=Date.now();const r=limits.get(k);if(r&&r.until>now){if(r.n>=max)fail(429,'Too many attempts. Try again in 15 minutes.');r.n++}else{if(limits.size>10000)limits.clear();limits.set(k,{n:1,until:now+900000})}}
function auth(req,required=true){const raw=req.headers.authorization?.startsWith('Bearer ')?req.headers.authorization.slice(7):req.headers.cookie?.split(';').map(s=>s.trim()).find(s=>s.startsWith('ridelink_session='))?.slice(17);if(!raw){if(required)fail(401,'Sign in required');return null}const u=db.prepare('SELECT users.* FROM sessions JOIN users ON users.id=sessions.user_id WHERE token_hash=? AND expires_at>? AND users.active=1').get(hashToken(raw),Date.now());if(!u){if(required)fail(401,'Session expired. Sign in again.');return null}if(u.role==='shop'&&!db.prepare("SELECT id FROM stores WHERE id=? AND status='active'").get(u.store_id))fail(403,'Your store is not active');return u;}
const requireRole=(u,...roles)=>{if(!roles.includes(u.role))fail(403,'Access denied')};
const audit=(u,action,record)=>db.prepare('INSERT INTO audit VALUES(?,?,?,?,?)').run(id(),u?.id||null,action,record,new Date().toISOString());
const session=(u,res)=>{const token=randomBytes(32).toString('base64url');db.prepare('DELETE FROM sessions WHERE expires_at<?').run(Date.now());db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hashToken(token),u.id,Date.now()+7*86400000);res.setHeader('Set-Cookie',`ridelink_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800${secure?'; Secure':''}`);return token;};
const currentSettings=()=>parse(db.prepare('SELECT payload FROM settings WHERE id=1').get());
const carRow=cid=>{const row=db.prepare('SELECT * FROM cars WHERE id=?').get(cid);if(!row)fail(404,'Car not found');return row};
const ownCar=(u,row)=>{requireRole(u,'shop','system');if(u.role==='shop'&&u.store_id!==row.store_id)fail(403,'Access denied')};
const activeStore=sid=>{if(!db.prepare("SELECT id FROM stores WHERE id=? AND status='active'").get(sid))fail(409,'Store is not active')};
const busy=(cid,start,end,except='')=>db.prepare("SELECT id FROM bookings WHERE car_id=? AND status='approved' AND start<? AND end>? AND id<>?").get(cid,end,start,except);
function transaction(f){db.exec('BEGIN IMMEDIATE');try{const result=f();db.exec('COMMIT');return result}catch(e){db.exec('ROLLBACK');throw e}}
function saveCar(input,u,cid){const old=cid?carRow(cid):null;if(old)ownCar(u,old);else requireRole(u,'shop','system');const storeId=old?.store_id||(u.role==='shop'?u.store_id:text(input.storeId,'store'));const image=text(input.image,'image',2900000);if(!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(image)&&!/^\/images\/[a-zA-Z0-9_.-]+$/.test(image)&&!/^https:\/\//.test(image))fail(400,'Invalid image');const status=choice(input.status,['available','maintenance'],'status');if(old&&status==='maintenance'&&db.prepare("SELECT id FROM bookings WHERE car_id=? AND status='approved' AND end>?").get(cid,today()))fail(409,'Resolve approved bookings before scheduling maintenance');const store=db.prepare('SELECT * FROM stores WHERE id=?').get(storeId);if(!store)fail(404,'Store not found');if(store.status!=='active')fail(409,'Store is not active');const car={id:cid||id(),storeId,name:text(input.name,'car name',100),city:store.city,category:choice(input.category,['Economy','Comfort','SUV','Premium'],'category'),price:num(input.price,'price',1,10000),deposit:num(input.deposit,'deposit',0,10000),eta:text(input.eta,'ETA',40),image,description:text(input.description,'description',1000),status,seats:num(input.seats,'seats',1,12)};if(!Number.isInteger(car.seats))fail(400,'Seats must be a whole number');db.prepare('INSERT INTO cars VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload').run(car.id,storeId,JSON.stringify(car));audit(u,'car.save',car.id);return car;}
const server=createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('Cache-Control','no-store');const url=new URL(req.url,'http://localhost');const path=url.pathname;const method=req.method;const send=(value,status=200)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(value));};try{
if(path.startsWith('/api/')&&!['GET','HEAD','OPTIONS'].includes(method)){if(req.headers.origin&&req.headers.origin!==origin)fail(403,'Origin not allowed');if(!String(req.headers['content-type']).startsWith('application/json'))fail(415,'Content-Type must be application/json');}
if(path==='/api/health')return send({ok:true});
if(path==='/api/auth/register'&&method==='POST'){rate(req,'register',8);const b=await body(req);const name=text(b.name,'name',100),mail=email(b.email),password=text(b.password,'password',256);if(password.length<12)fail(400,'Use a password with at least 12 characters');let u;try{u=registerCustomer(db,name,mail,password)}catch(e){if(String(e).includes('UNIQUE'))fail(409,'Unable to create account with this email');throw e}const token=session(u,res);return send({user:publicUser(u),token},201)}
if(path==='/api/auth/login'&&method==='POST'){rate(req,'login');const b=await body(req);const u=db.prepare('SELECT * FROM users WHERE email=?').get(email(b.email));if(!u||!u.active||!verifyPassword(text(b.password,'password',256),u.password_hash))fail(401,'Invalid email or password');if(u.role==='shop')activeStore(u.store_id);const token=session(u,res);audit(u,'login',u.id);return send({user:publicUser(u),token})}
if(path==='/api/auth/me'&&method==='GET')return send({user:publicUser(auth(req))});
if(path==='/api/auth/logout'&&method==='POST'){const u=auth(req);const raw=req.headers.authorization?.slice(7)||req.headers.cookie?.split(';').map(s=>s.trim()).find(s=>s.startsWith('ridelink_session='))?.slice(17);if(raw)db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hashToken(raw));res.setHeader('Set-Cookie',`ridelink_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0${secure?'; Secure':''}`);return send({ok:true})}
if(path==='/api/auth/password'&&method==='PUT'){const u=auth(req);rate(req,'password',8);const b=await body(req);if(!verifyPassword(text(b.currentPassword,'current password',256),u.password_hash))fail(401,'Current password is incorrect');const password=text(b.newPassword,'new password',256);if(password.length<12)fail(400,'Use a password with at least 12 characters');transaction(()=>{db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(passwordHash(password),u.id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(u.id);audit(u,'password.change',u.id)});const token=session(u,res);return send({token})}
if(path==='/api/auth/account'&&method==='DELETE'){const u=auth(req);requireRole(u,'customer');const b=await body(req);if(!verifyPassword(text(b.password,'password',256),u.password_hash))fail(401,'Password is incorrect');transaction(()=>{if(db.prepare("SELECT id FROM bookings WHERE user_id=? AND status IN ('pending','approved')").get(u.id))fail(409,'Cancel or finish active bookings before deleting your account');for(const row of db.prepare('SELECT * FROM bookings WHERE user_id=?').all(u.id)){const old=parse(row);db.prepare('UPDATE bookings SET payload=? WHERE id=?').run(JSON.stringify({...old,customer:'Deleted customer',phone:'',address:''}),row.id)}db.prepare('DELETE FROM reviews WHERE user_id=?').run(u.id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(u.id);db.prepare('UPDATE users SET email=?,name=?,password_hash=?,active=0 WHERE id=?').run('deleted-'+u.id+'@invalid.local','Deleted customer',passwordHash(randomBytes(32).toString('hex')),u.id);audit(u,'account.delete',u.id)});res.setHeader('Set-Cookie','ridelink_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return send({ok:true})}
if(path==='/api/catalog'&&method==='GET'){const stores=db.prepare("SELECT * FROM stores WHERE status='active'").all();const cars=db.prepare("SELECT cars.payload FROM cars JOIN stores ON stores.id=cars.store_id WHERE stores.status='active'").all().map(parse).filter(c=>c.status==='available');const reviews=db.prepare("SELECT reviews.id,users.name,reviews.store_id AS storeId,rating,text,status FROM reviews JOIN users ON users.id=reviews.user_id WHERE status='published'").all();return send({cars,stores:stores.map(({email,...s})=>s),reviews,settings:currentSettings()})}
if(path==='/api/bookings'&&method==='GET'){const u=auth(req);const rows=u.role==='system'?db.prepare('SELECT payload FROM bookings ORDER BY created_at DESC').all():u.role==='shop'?db.prepare('SELECT payload FROM bookings WHERE store_id=? ORDER BY created_at DESC').all(u.store_id):db.prepare('SELECT payload FROM bookings WHERE user_id=? ORDER BY created_at DESC').all(u.id);return send(rows.map(parse))}
if(path==='/api/bookings'&&method==='POST'){const u=auth(req);requireRole(u,'customer');rate(req,'booking',30);const b=await body(req);const row=carRow(text(b.carId,'car'));const car=parse(row);const start=date(b.start),end=date(b.end);const days=(Date.parse(end)-Date.parse(start))/86400000;if(start<today()||days<1||days>365)fail(400,'Choose valid rental dates of 1–365 days');const phone=text(b.phone,'phone',25);if(!/^\+?[\d\s()-]{8,25}$/.test(phone))fail(400,'Invalid phone number');const delivery=b.delivery===true;const address=delivery?text(b.address,'address',300):'';choice(b.payment,['Cash'],'payment method');const booking=transaction(()=>{activeStore(row.store_id);if(car.status!=='available'||busy(car.id,start,end))fail(409,'Car is unavailable for these dates');const fee=delivery?currentSettings().deliveryFee:0;const item={id:'RL-'+id(),userId:u.id,storeId:row.store_id,carId:car.id,carName:car.name,customer:u.name,phone,start,end,days,rate:car.price,fee,total:Math.round((days*car.price+fee)*100)/100,deposit:car.deposit,delivery,address,eta:car.eta,payment:'Cash',status:'pending',createdAt:new Date().toISOString()};db.prepare('INSERT INTO bookings VALUES(?,?,?,?,?,?,?,?,?)').run(item.id,u.id,item.storeId,item.carId,start,end,'pending',JSON.stringify(item),item.createdAt);audit(u,'booking.create',item.id);return item});return send(booking,201)}
const bookingMatch=path.match(/^\/api\/bookings\/([^/]+)$/);if(bookingMatch&&method==='PATCH'){const u=auth(req);const b=await body(req);const booking=transaction(()=>{const row=db.prepare('SELECT * FROM bookings WHERE id=?').get(bookingMatch[1]);if(!row)fail(404,'Booking not found');const old=parse(row);const status=choice(b.status,['approved','rejected','cancelled','completed'],'status');if(u.role==='customer'){if(row.user_id!==u.id||status!=='cancelled'||!['pending','approved'].includes(old.status))fail(403,'Access denied')}else{if(u.role==='shop'&&row.store_id!==u.store_id)fail(403,'Access denied');const transitions={pending:['approved','rejected'],approved:['cancelled','completed']};if(!transitions[old.status]?.includes(status))fail(409,'Invalid booking transition');if(status==='approved'){activeStore(row.store_id);const car=parse(carRow(row.car_id));if(row.end<=today()||car.status!=='available'||busy(row.car_id,row.start,row.end,row.id))fail(409,'Booking is expired or conflicts with another reservation')}}const next={...old,status};db.prepare('UPDATE bookings SET status=?,payload=? WHERE id=?').run(status,JSON.stringify(next),row.id);audit(u,'booking.'+status,row.id);return next});return send(booking)}
if(path==='/api/reviews'&&method==='POST'){const u=auth(req);requireRole(u,'customer');const b=await body(req);const booking=db.prepare("SELECT * FROM bookings WHERE id=? AND user_id=? AND status='completed'").get(text(b.bookingId,'booking'),u.id);if(!booking)fail(403,'Only completed rentals can be reviewed');const rating=num(b.rating,'rating',1,5);if(!Number.isInteger(rating))fail(400,'Invalid rating');try{db.prepare('INSERT INTO reviews VALUES(?,?,?,?,?,?,?)').run(id(),u.id,booking.id,booking.store_id,rating,text(b.text,'review',2000),'pending')}catch(e){if(String(e).includes('UNIQUE'))fail(409,'This booking already has a review');throw e}return send({ok:true},201)}
if(path==='/api/admin/state'&&method==='GET'){const u=auth(req);requireRole(u,'shop','system');const system=u.role==='system';const stores=system?db.prepare('SELECT * FROM stores').all():db.prepare('SELECT * FROM stores WHERE id=?').all(u.store_id);const cars=(system?db.prepare('SELECT payload FROM cars').all():db.prepare('SELECT payload FROM cars WHERE store_id=?').all(u.store_id)).map(parse);const bookings=(system?db.prepare('SELECT payload FROM bookings ORDER BY created_at DESC').all():db.prepare('SELECT payload FROM bookings WHERE store_id=? ORDER BY created_at DESC').all(u.store_id)).map(parse);const admins=system?db.prepare("SELECT * FROM users WHERE role='shop'").all().map(publicUser):[];const reviews=system?db.prepare('SELECT reviews.id,users.name,reviews.store_id AS storeId,rating,text,status FROM reviews JOIN users ON users.id=reviews.user_id').all():[];return send({cars,bookings,stores,admins,reviews,settings:currentSettings()})}
if(path==='/api/admin/cars'&&method==='POST'){const u=auth(req);return send(saveCar(await body(req),u),201)}
const carMatch=path.match(/^\/api\/admin\/cars\/([^/]+)$/);if(carMatch&&method==='PUT'){const u=auth(req);return send(saveCar(await body(req),u,carMatch[1]))}if(carMatch&&method==='DELETE'){const u=auth(req);const row=carRow(carMatch[1]);ownCar(u,row);transaction(()=>{if(db.prepare("SELECT id FROM bookings WHERE car_id=? AND status IN ('pending','approved')").get(row.id))fail(409,'Resolve active bookings before deleting this car');db.prepare('DELETE FROM cars WHERE id=?').run(row.id);audit(u,'car.delete',row.id)});return send({ok:true})}
if(path==='/api/admin/stores'&&method==='POST'){const u=auth(req);requireRole(u,'system');const b=await body(req);const s={id:id(),name:text(b.name,'store name',100),city:text(b.city,'city',60),email:email(b.email),status:'pending'};db.prepare('INSERT INTO stores VALUES(?,?,?,?,?)').run(s.id,s.name,s.city,s.email,s.status);audit(u,'store.create',s.id);return send(s,201)}
const storeMatch=path.match(/^\/api\/admin\/stores\/([^/]+)$/);if(storeMatch&&['PATCH','DELETE'].includes(method)){const u=auth(req);requireRole(u,'system');const s=db.prepare('SELECT * FROM stores WHERE id=?').get(storeMatch[1]);if(!s)fail(404,'Store not found');if(method==='PATCH'){const b=await body(req);const status=choice(b.status,['active','pending','suspended'],'store status');db.prepare('UPDATE stores SET status=? WHERE id=?').run(status,s.id);audit(u,'store.'+status,s.id);return send({...s,status})}transaction(()=>{if(db.prepare("SELECT id FROM bookings WHERE store_id=? AND status IN ('pending','approved')").get(s.id))fail(409,'Resolve active bookings before deleting this store');db.prepare('DELETE FROM cars WHERE store_id=?').run(s.id);db.prepare('UPDATE users SET active=0 WHERE store_id=?').run(s.id);db.prepare('DELETE FROM reviews WHERE store_id=?').run(s.id);db.prepare('DELETE FROM stores WHERE id=?').run(s.id);audit(u,'store.delete',s.id)});return send({ok:true})}
if(path==='/api/admin/users'&&method==='POST'){const u=auth(req);requireRole(u,'system');const b=await body(req);const store=text(b.storeId,'store');if(!db.prepare('SELECT id FROM stores WHERE id=?').get(store))fail(400,'Store not found');const password=text(b.password,'password',256);if(password.length<12)fail(400,'Use at least 12 characters');const uid=id();try{db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,?,?)').run(uid,email(b.email),text(b.name,'name',100),passwordHash(password),'shop',store,1,new Date().toISOString())}catch(e){if(String(e).includes('UNIQUE'))fail(409,'Email is already registered');throw e}audit(u,'admin.create',uid);return send(publicUser(db.prepare('SELECT * FROM users WHERE id=?').get(uid)),201)}
const userMatch=path.match(/^\/api\/admin\/users\/([^/]+)$/);if(userMatch&&['PATCH','DELETE'].includes(method)){const u=auth(req);requireRole(u,'system');const target=db.prepare("SELECT * FROM users WHERE id=? AND role='shop'").get(userMatch[1]);if(!target)fail(404,'Shop admin not found');const b=method==='PATCH'?await body(req):{};if(method==='PATCH'){if(typeof b.active!=='boolean')fail(400,'Invalid account status');db.prepare('UPDATE users SET active=? WHERE id=?').run(b.active?1:0,target.id)}else db.prepare('UPDATE users SET active=0 WHERE id=?').run(target.id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(target.id);audit(u,'admin.update',target.id);return send({ok:true})}
const reviewMatch=path.match(/^\/api\/admin\/reviews\/([^/]+)$/);if(reviewMatch&&method==='PATCH'){const u=auth(req);requireRole(u,'system');const b=await body(req);const status=choice(b.status,['published','hidden','pending'],'review status');const result=db.prepare('UPDATE reviews SET status=? WHERE id=?').run(status,reviewMatch[1]);if(!result.changes)fail(404,'Review not found');audit(u,'review.'+status,reviewMatch[1]);return send({ok:true})}
if(path==='/api/admin/settings'&&method==='PUT'){const u=auth(req);requireRole(u,'system');const b=await body(req);const settings={deliveryFee:num(b.deliveryFee,'delivery fee',0,1000),promotion:typeof b.promotion==='string'?b.promotion.trim().slice(0,200):''};db.prepare('UPDATE settings SET payload=? WHERE id=1').run(JSON.stringify(settings));audit(u,'settings.update','1');return send(settings)}
if(path.startsWith('/api/'))fail(404,'Endpoint not found');
if(method!=='GET'&&method!=='HEAD')fail(405,'Method not allowed');const root=resolve(ROOT,'dist');let file=resolve(root,'.'+decodeURIComponent(path));if(!file.startsWith(root+sep)&&file!==root)fail(403,'Access denied');if(!existsSync(file)||!extname(file))file=resolve(root,'index.html');if(!existsSync(file))fail(404,'Build the admin website first');const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.jpg':'image/jpeg','.png':'image/png','.webp':'image/webp'};res.setHeader('Content-Type',mime[extname(file)]||'application/octet-stream');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");res.end(readFileSync(file));
}catch(e){if(!e.status)console.error(e);send({error:e.status?e.message:'Internal server error'},e.status||500)}});
return {server,db};}
if(process.argv[1]===fileURLToPath(import.meta.url)){const {server}=createApp();server.listen(Number(process.env.PORT||3001),process.env.HOST||'127.0.0.1',()=>console.log(`RideLink server: http://${process.env.HOST||'127.0.0.1'}:${process.env.PORT||3001}`));}

