import {useEffect,useState} from 'react';
import {Globe,LogOut,ShieldCheck} from 'lucide-react';
import {AdminArea,Lang,Logo} from './AdminDashboard';
import {arabic} from './translations';
import type {Data} from './domain';
type User={id:string;name:string;email:string;role:'customer'|'shop'|'system';storeId:string|null};
export async function api(path:string,method='GET',data?:unknown){const r=await fetch('/api'+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json'},...(data!==undefined?{body:JSON.stringify(data)}:{})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Request failed');return b;}
export default function ProductionApp(){const [user,setUser]=useState<User|null>(null);const [data,setData]=useState<Data|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');const [ar,setAr]=useState(false);const t=(s:string)=>ar?arabic[s]||s:s;
useEffect(()=>{document.documentElement.lang=ar?'ar':'en';document.documentElement.dir=ar?'rtl':'ltr'},[ar]);
async function refresh(){setData(await api('/admin/state'))}
useEffect(()=>{api('/auth/me').then(async b=>{if(b.user.role==='customer')throw new Error('This website is for shop and system administrators.');setUser(b.user);await refresh()}).catch(e=>{if(!e.message.includes('Sign in')&&!e.message.includes('Session expired'))setError(e.message)}).finally(()=>setLoading(false))},[]);
async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const result=await api('/auth/login','POST',{email:f.get('email'),password:f.get('password')});if(result.user.role==='customer'){await api('/auth/logout','POST',{});throw new Error('Use the customer mobile app for this account.')}setUser(result.user);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
async function logout(){setBusy(true);try{await api('/auth/logout','POST',{});setUser(null);setData(null)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
async function update(change:(d:Data)=>Data){if(!data||busy)return;const next=change(data);setBusy(true);setError('');setSuccess('');try{for(const group of ['cars','stores','admins','reviews'] as const){const before=data[group] as any[],after=next[group] as any[];for(const item of after){const old=before.find(x=>x.id===item.id);if(!old){await api('/admin/'+({cars:'cars',stores:'stores',admins:'users',reviews:'reviews'}[group]),'POST',item)}else if(JSON.stringify(old)!==JSON.stringify(item)){await api('/admin/'+({cars:'cars',stores:'stores',admins:'users',reviews:'reviews'}[group])+'/'+item.id,group==='cars'?'PUT':'PATCH',item)}}for(const old of before){if(!after.some(x=>x.id===old.id)){if(group==='reviews')continue;await api('/admin/'+({cars:'cars',stores:'stores',admins:'users',reviews:'reviews'}[group])+'/'+old.id,'DELETE')}}}for(const b of next.bookings){const old=data.bookings.find(x=>x.id===b.id);if(old&&old.status!==b.status)await api('/bookings/'+b.id,'PATCH',{status:b.status})}if(JSON.stringify(data.settings)!==JSON.stringify(next.settings))await api('/admin/settings','PUT',next.settings);await refresh();setSuccess(t('Changes saved'))}catch(e){setError((e as Error).message);try{await refresh()}catch{}}finally{setBusy(false)}}
return <Lang.Provider value={{ar,t}}><header className="topbar"><Logo/><span className="muted">{t('Administration')}</span><div className="actions"><button className="language" onClick={()=>setAr(!ar)}><Globe size={18}/>{ar?'English':'العربية'}</button>{user&&<button className="button secondary" onClick={logout} disabled={busy}><LogOut size={16}/>{t('Log out')}</button>}</div></header>{loading?<main className="empty">{t('Connecting to RideLink…')}</main>:user&&data?<><div className="account-strip"><ShieldCheck size={16}/>{user.name} · {user.email}<span>{busy?t('Saving…'):t('Connected to server')}</span></div>{error&&<div className="error" role="alert">{error}</div>}{success&&<div className="info" role="status">{success}</div>}<fieldset disabled={busy} className="admin-fieldset"><AdminArea key={user.id} system={user.role==='system'} data={data} update={update} notify={()=>{}} setAr={setAr} storeId={user.storeId||''} onLogout={logout}/></fieldset></>:<main className="login-page"><section className="login-story"><p className="eyebrow">RIDELINK PARTNERS</p><h1>{t('Your fleet. One workspace.')}</h1><p>{t('Manage your cars, review booking requests, and keep your business moving.')}</p><ShieldCheck size={70}/></section><form className="panel login-form" onSubmit={login}><h1>{t('Sign in')}</h1><p className="muted">{t('Shop and system administrators')}</p><label>{t('Email')}<input type="email" name="email" autoComplete="username" required/></label><label>{t('Password')}<input type="password" name="password" autoComplete="current-password" required/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="button full" disabled={busy}>{t(busy?'Signing in…':'Sign in')}</button></form></main>}<footer><Logo/><span>{t('Your journey. Your way.')}</span></footer></Lang.Provider>
}
